### ISSUE TITLE
requirements.txt is too strict

### ISSUE THREAD

**Issue by cameronfr** [NeuroDataDesign/mvlearn#38]
for example there's the line `numpy==1.17.2` whereas `numpy>=1.17` or even just `numpy` would probably be fine and prevent people from running into issues installing different versions of packages they already have.

We can probably change this by figuring out which requirements need to be strict and changing the rest to not be `==`

**Comment by rflperry** [comment]
Seems fine by me. Make a PR, as simple as editing on the webbrowser
