### ISSUE TITLE
put this on pypi

### ISSUE THREAD

**Issue by jovo** [NeuroDataDesign/mvlearn#52]

**Comment by jovo** [comment]
since multiview is taken, maybe we call it:
`skmultiview`
?

**Comment by rguo123** [comment]
Done! We went with the name `mvlearn`. There's probably some installation problems since this is first deployment but right now I can pip install the package and run through a couple tutorials without any problem.

**Comment by rguo123** [comment]
Closing this issue for now unless I run into major pypi problems
