### ISSUE TITLE
Doc build fails due to extensive memory usage

### ISSUE THREAD

**Issue by rguo123** [NeuroDataDesign/mvlearn#61]
This is coming from readthedocs when pip installing all our libraries. 

The build will sometimes pass and sometimes fail. I'm guessing this depends on how many resources readthedocs has available at the time.

**Comment by rflperry** [comment]
I haven't had that issue but tensorflow is a lot of memory, maybe that is. [https://mvlearn.netlify.com/index.html](https://mvlearn.netlify.com/index.html) is currently up although needs some work, so vote to close this issue.

**Comment by rguo123** [comment]
netlify looks great! and sounds good ill go ahead and close it
